### ISSUE TITLE
Code BUG!

### ISSUE THREAD

**Issue by sasiyaluba** [libp2p/js-libp2p-example-circuit-relay#2]
origin code:
`const conn = await node.dial(relayAddr)`
correct code:
`const conn = await node.dial(multiaddr(relayAddr))`

if you use origin code,then program will abort and throw error like:
`
file:///home/kaka/code/libp2p_test/node_modules/libp2p/dist/src/get-peer.js:17
        const peerIdStr = peer[0].getPeerId();
                                  ^

TypeError: peer[0].getPeerId is not a function
    at getPeerAddress (file:///home/kaka/code/libp2p_test/node_modules/libp2p/dist/src/get-peer.js:17:35)
    at DefaultConnectionManager.openConnection (file:///home/kaka/code/libp2p_test/node_modules/libp2p/dist/src/connection-manager/index.js:306:28)
    at Libp2pNode.dial (file:///home/kaka/code/libp2p_test/node_modules/libp2p/dist/src/libp2p.js:225:50)
    at file:///home/kaka/code/libp2p_test/circuit_replay/listen.js:30:25

Node.js v21.6.2
`

**Comment by tebicap** [comment]
Also in the third step the tutorial script will throw an error because of misconfiguration:

throw new UnmetServiceDependenciesError(`Service "${getServiceName(service)}" required capability "${capability}" but it was not provided by any component, you may need to add additional configuration when creating your node.`);
                      ^

UnmetServiceDependenciesError: Service "@libp2p/circuit-relay-v2-transport" required capability "@libp2p/identify" but it was not provided by any component, you may need to add additional configuration when creating your node.
...


Missing lines:

import { circuitRelayTransport } from '@libp2p/circuit-relay-v2'
import { identify } from '@libp2p/identify'
...
  transports: [webSockets(), circuitRelayTransport()], // <- circuitRelayTransport() added
...
  services: {
    identify: identify()
  }
